export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_REVIEW_DATA: 'SET_REVIEW_DATA',
	RESET_REVIEW_DATA: 'RESET_REVIEW_DATA',
};


